import { AppleCardsCarouselDemo } from "@/components/CardsCarousel/CardsCarousel";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About | Yash Raj Portfolio",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <AppleCardsCarouselDemo />
    </div>
  );
};

export default page;
